### ISSUE TITLE
Change license to LGPLv2.1, MIT or any other more permissive license

### ISSUE THREAD

**Issue by dmach** [parlt91/libeconf#3]
GPLv2 is quite restrictive for a library.
We can't use it with libdnf, because it's LGPLv2.1.
Could you consider changing the license to something more permissive?

**Comment by Conan-Kudo** [comment]
I'd be in favor of LGPLv2+ rather than getting any more permissive.

**Comment by parlt91** [comment]
I made a pull request to change the license to LGPL-2.0
